// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_router.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transport_5frouter_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transport_5frouter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transport_5frouter_2eproto;
namespace router {
class RouterSettings;
class RouterSettingsDefaultTypeInternal;
extern RouterSettingsDefaultTypeInternal _RouterSettings_default_instance_;
}  // namespace router
PROTOBUF_NAMESPACE_OPEN
template<> ::router::RouterSettings* Arena::CreateMaybeMessage<::router::RouterSettings>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace router {

// ===================================================================

class RouterSettings PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:router.RouterSettings) */ {
 public:
  inline RouterSettings() : RouterSettings(nullptr) {}
  virtual ~RouterSettings();

  RouterSettings(const RouterSettings& from);
  RouterSettings(RouterSettings&& from) noexcept
    : RouterSettings() {
    *this = ::std::move(from);
  }

  inline RouterSettings& operator=(const RouterSettings& from) {
    CopyFrom(from);
    return *this;
  }
  inline RouterSettings& operator=(RouterSettings&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RouterSettings& default_instance();

  static inline const RouterSettings* internal_default_instance() {
    return reinterpret_cast<const RouterSettings*>(
               &_RouterSettings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RouterSettings& a, RouterSettings& b) {
    a.Swap(&b);
  }
  inline void Swap(RouterSettings* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RouterSettings* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RouterSettings* New() const final {
    return CreateMaybeMessage<RouterSettings>(nullptr);
  }

  RouterSettings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RouterSettings>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RouterSettings& from);
  void MergeFrom(const RouterSettings& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RouterSettings* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "router.RouterSettings";
  }
  protected:
  explicit RouterSettings(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_transport_5frouter_2eproto);
    return ::descriptor_table_transport_5frouter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBusSpeedFieldNumber = 1,
    kStopWaitingTimeFieldNumber = 2,
  };
  // double bus_speed = 1;
  void clear_bus_speed();
  double bus_speed() const;
  void set_bus_speed(double value);
  private:
  double _internal_bus_speed() const;
  void _internal_set_bus_speed(double value);
  public:

  // int32 stop_waiting_time = 2;
  void clear_stop_waiting_time();
  ::PROTOBUF_NAMESPACE_ID::int32 stop_waiting_time() const;
  void set_stop_waiting_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_stop_waiting_time() const;
  void _internal_set_stop_waiting_time(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:router.RouterSettings)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double bus_speed_;
  ::PROTOBUF_NAMESPACE_ID::int32 stop_waiting_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transport_5frouter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RouterSettings

// double bus_speed = 1;
inline void RouterSettings::clear_bus_speed() {
  bus_speed_ = 0;
}
inline double RouterSettings::_internal_bus_speed() const {
  return bus_speed_;
}
inline double RouterSettings::bus_speed() const {
  // @@protoc_insertion_point(field_get:router.RouterSettings.bus_speed)
  return _internal_bus_speed();
}
inline void RouterSettings::_internal_set_bus_speed(double value) {
  
  bus_speed_ = value;
}
inline void RouterSettings::set_bus_speed(double value) {
  _internal_set_bus_speed(value);
  // @@protoc_insertion_point(field_set:router.RouterSettings.bus_speed)
}

// int32 stop_waiting_time = 2;
inline void RouterSettings::clear_stop_waiting_time() {
  stop_waiting_time_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RouterSettings::_internal_stop_waiting_time() const {
  return stop_waiting_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RouterSettings::stop_waiting_time() const {
  // @@protoc_insertion_point(field_get:router.RouterSettings.stop_waiting_time)
  return _internal_stop_waiting_time();
}
inline void RouterSettings::_internal_set_stop_waiting_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  stop_waiting_time_ = value;
}
inline void RouterSettings::set_stop_waiting_time(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_stop_waiting_time(value);
  // @@protoc_insertion_point(field_set:router.RouterSettings.stop_waiting_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace router

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transport_5frouter_2eproto
